"""Agent Definitions — all 121 trading agents for the multi-agent voting system.

Each agent is an AgentDNA instance with unique personality parameters,
sector expertise, and strategy preferences. Agents with overlapping skills
share a peer_group so they pre-vote together before the main vote.
"""

from typing import Dict, List, Optional

from src.agents.agent_dna import AgentDNA


def build_all_agents() -> List[AgentDNA]:
    """Build and return all 121 trading agent definitions."""
    agents = [
        # =====================================================================
        # SECTOR SPECIALISTS (1-11)
        # =====================================================================
        AgentDNA(
            agent_id="tech_momentum",
            display_name="Tech Momentum",
            primary_sectors=["technology"],
            secondary_sectors=["semiconductors", "cloud_saas"],
            primary_strategy="momentum",
            risk_appetite=0.5,
            contrarian_factor=0.15,
            conviction_style=0.5,
            regime_sensitivity=0.4,
            lookback_days=50,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="tech_cluster",
        ),
        AgentDNA(
            agent_id="healthcare_event",
            display_name="Healthcare Event-Driven",
            primary_sectors=["healthcare"],
            secondary_sectors=["biotech", "pharma"],
            primary_strategy="event_driven",
            risk_appetite=0.3,
            contrarian_factor=0.1,
            conviction_style=0.6,
            regime_sensitivity=0.3,
            lookback_days=30,
            holding_period="swing",
            min_confidence=0.65,
            max_picks_per_scan=4,
            peer_group="healthcare_cluster",
        ),
        AgentDNA(
            agent_id="financial_value",
            display_name="Financial Value",
            primary_sectors=["financials"],
            secondary_sectors=["banks", "insurance"],
            primary_strategy="value",
            risk_appetite=0.5,
            contrarian_factor=0.2,
            conviction_style=0.5,
            regime_sensitivity=0.3,
            lookback_days=120,
            holding_period="position",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="financials_cluster",
        ),
        AgentDNA(
            agent_id="energy_mean_rev",
            display_name="Energy Mean Reversion",
            primary_sectors=["energy"],
            secondary_sectors=["oil_gas", "renewables"],
            primary_strategy="mean_reversion",
            risk_appetite=0.7,
            contrarian_factor=0.3,
            conviction_style=0.5,
            regime_sensitivity=0.4,
            lookback_days=40,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="energy_cluster",
        ),
        AgentDNA(
            agent_id="consumer_disc_growth",
            display_name="Consumer Discretionary Growth",
            primary_sectors=["consumer_discretionary"],
            secondary_sectors=["retail", "auto"],
            primary_strategy="growth",
            risk_appetite=0.5,
            contrarian_factor=0.15,
            conviction_style=0.5,
            regime_sensitivity=0.3,
            lookback_days=60,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="consumer_cluster",
        ),
        AgentDNA(
            agent_id="consumer_staples_value",
            display_name="Consumer Staples Value",
            primary_sectors=["consumer_staples"],
            secondary_sectors=["food_beverage"],
            primary_strategy="value",
            risk_appetite=0.3,
            contrarian_factor=0.1,
            conviction_style=0.4,
            regime_sensitivity=0.2,
            lookback_days=200,
            holding_period="position",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="consumer_cluster",
        ),
        AgentDNA(
            agent_id="industrial_momentum",
            display_name="Industrial Momentum",
            primary_sectors=["industrials"],
            secondary_sectors=["defense", "aerospace"],
            primary_strategy="momentum",
            risk_appetite=0.5,
            contrarian_factor=0.15,
            conviction_style=0.5,
            regime_sensitivity=0.35,
            lookback_days=50,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="industrials_cluster",
        ),
        AgentDNA(
            agent_id="materials_breakout",
            display_name="Materials Breakout",
            primary_sectors=["materials"],
            secondary_sectors=["mining"],
            primary_strategy="breakout",
            risk_appetite=0.7,
            contrarian_factor=0.2,
            conviction_style=0.6,
            regime_sensitivity=0.4,
            lookback_days=30,
            holding_period="scalp",
            min_confidence=0.65,
            max_picks_per_scan=4,
            peer_group="materials_cluster",
        ),
        AgentDNA(
            agent_id="real_estate_value",
            display_name="Real Estate Value",
            primary_sectors=["real_estate"],
            secondary_sectors=["reits"],
            primary_strategy="value",
            risk_appetite=0.3,
            contrarian_factor=0.1,
            conviction_style=0.4,
            regime_sensitivity=0.3,
            lookback_days=120,
            holding_period="position",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="real_estate_cluster",
        ),
        AgentDNA(
            agent_id="utilities_mean_rev",
            display_name="Utilities Mean Reversion",
            primary_sectors=["utilities"],
            secondary_sectors=[],
            primary_strategy="mean_reversion",
            risk_appetite=0.3,
            contrarian_factor=0.15,
            conviction_style=0.4,
            regime_sensitivity=0.2,
            lookback_days=60,
            holding_period="position",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="utilities_cluster",
        ),
        AgentDNA(
            agent_id="comms_sentiment",
            display_name="Communication Services Sentiment",
            primary_sectors=["communication_services"],
            secondary_sectors=["media", "telecom"],
            primary_strategy="sentiment",
            risk_appetite=0.5,
            contrarian_factor=0.2,
            conviction_style=0.5,
            regime_sensitivity=0.35,
            lookback_days=20,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="comms_cluster",
        ),

        # =====================================================================
        # STRATEGY PURISTS (12-19)
        # =====================================================================
        AgentDNA(
            agent_id="pure_momentum",
            display_name="Pure Momentum",
            primary_sectors=["all"],
            primary_strategy="momentum",
            risk_appetite=0.5,
            contrarian_factor=0.1,
            conviction_style=0.5,
            regime_sensitivity=0.3,
            lookback_days=50,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="momentum_cluster",
        ),
        AgentDNA(
            agent_id="pure_mean_rev",
            display_name="Pure Mean Reversion",
            primary_sectors=["all"],
            primary_strategy="mean_reversion",
            risk_appetite=0.5,
            contrarian_factor=0.3,
            conviction_style=0.5,
            regime_sensitivity=0.3,
            lookback_days=40,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="mean_rev_cluster",
        ),
        AgentDNA(
            agent_id="pure_value",
            display_name="Pure Value",
            primary_sectors=["all"],
            primary_strategy="value",
            risk_appetite=0.3,
            contrarian_factor=0.2,
            conviction_style=0.5,
            regime_sensitivity=0.2,
            lookback_days=200,
            holding_period="position",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="value_cluster",
        ),
        AgentDNA(
            agent_id="pure_growth",
            display_name="Pure Growth",
            primary_sectors=["all"],
            primary_strategy="growth",
            risk_appetite=0.5,
            contrarian_factor=0.1,
            conviction_style=0.5,
            regime_sensitivity=0.3,
            lookback_days=60,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="growth_cluster",
        ),
        AgentDNA(
            agent_id="pure_event",
            display_name="Pure Event-Driven",
            primary_sectors=["all"],
            primary_strategy="event_driven",
            risk_appetite=0.7,
            contrarian_factor=0.15,
            conviction_style=0.6,
            regime_sensitivity=0.4,
            lookback_days=20,
            holding_period="scalp",
            min_confidence=0.65,
            max_picks_per_scan=4,
            peer_group="event_cluster",
        ),
        AgentDNA(
            agent_id="pure_volatility",
            display_name="Pure Volatility",
            primary_sectors=["all"],
            primary_strategy="volatility",
            risk_appetite=0.5,
            contrarian_factor=0.2,
            conviction_style=0.5,
            regime_sensitivity=0.5,
            lookback_days=30,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="volatility_cluster",
        ),
        AgentDNA(
            agent_id="pure_sentiment",
            display_name="Pure Sentiment",
            primary_sectors=["all"],
            primary_strategy="sentiment",
            risk_appetite=0.5,
            contrarian_factor=0.2,
            conviction_style=0.5,
            regime_sensitivity=0.3,
            lookback_days=20,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="sentiment_cluster",
        ),
        AgentDNA(
            agent_id="pure_breakout",
            display_name="Pure Breakout",
            primary_sectors=["all"],
            primary_strategy="breakout",
            risk_appetite=0.7,
            contrarian_factor=0.1,
            conviction_style=0.6,
            regime_sensitivity=0.4,
            lookback_days=20,
            holding_period="scalp",
            min_confidence=0.65,
            max_picks_per_scan=4,
            peer_group="breakout_cluster",
        ),

        # =====================================================================
        # TIMEFRAME SPECIALISTS (20-23)
        # =====================================================================
        AgentDNA(
            agent_id="scalper",
            display_name="Scalper",
            primary_sectors=["all"],
            primary_strategy="breakout",
            risk_appetite=0.8,
            contrarian_factor=0.3,
            conviction_style=0.6,
            regime_sensitivity=0.4,
            lookback_days=10,
            holding_period="scalp",
            min_confidence=0.65,
            max_picks_per_scan=6,
            peer_group="scalp_cluster",
        ),
        AgentDNA(
            agent_id="swing_trader",
            display_name="Swing Trader",
            primary_sectors=["all"],
            primary_strategy="momentum",
            risk_appetite=0.5,
            contrarian_factor=0.2,
            conviction_style=0.5,
            regime_sensitivity=0.3,
            lookback_days=50,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="swing_cluster",
        ),
        AgentDNA(
            agent_id="position_trader",
            display_name="Position Trader",
            primary_sectors=["all"],
            primary_strategy="value",
            secondary_strategy="growth",
            risk_appetite=0.3,
            contrarian_factor=0.1,
            conviction_style=0.5,
            regime_sensitivity=0.2,
            lookback_days=120,
            holding_period="position",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="position_cluster",
        ),
        AgentDNA(
            agent_id="macro_trader",
            display_name="Macro Trader",
            primary_sectors=["all"],
            primary_strategy="value",
            risk_appetite=0.2,
            contrarian_factor=0.15,
            conviction_style=0.4,
            regime_sensitivity=0.5,
            lookback_days=252,
            holding_period="macro",
            min_confidence=0.65,
            max_picks_per_scan=4,
            peer_group="macro_cluster",
        ),

        # =====================================================================
        # CONTRARIAN SPECIALISTS (24-27)
        # =====================================================================
        AgentDNA(
            agent_id="contrarian_tech",
            display_name="Contrarian Tech",
            primary_sectors=["technology"],
            secondary_sectors=["semiconductors", "cloud_saas"],
            primary_strategy="mean_reversion",
            risk_appetite=0.5,
            contrarian_factor=0.8,
            conviction_style=0.6,
            regime_sensitivity=0.3,
            lookback_days=40,
            holding_period="swing",
            min_confidence=0.65,
            max_picks_per_scan=4,
            peer_group="contrarian_cluster",
        ),
        AgentDNA(
            agent_id="contrarian_broad",
            display_name="Contrarian Broad Market",
            primary_sectors=["all"],
            primary_strategy="mean_reversion",
            risk_appetite=0.5,
            contrarian_factor=0.9,
            conviction_style=0.6,
            regime_sensitivity=0.3,
            lookback_days=30,
            holding_period="swing",
            min_confidence=0.65,
            max_picks_per_scan=4,
            peer_group="contrarian_cluster",
        ),
        AgentDNA(
            agent_id="contrarian_value",
            display_name="Contrarian Value",
            primary_sectors=["all"],
            primary_strategy="value",
            risk_appetite=0.3,
            contrarian_factor=0.7,
            conviction_style=0.5,
            regime_sensitivity=0.2,
            lookback_days=200,
            holding_period="position",
            min_confidence=0.65,
            max_picks_per_scan=4,
            peer_group="contrarian_cluster",
        ),
        AgentDNA(
            agent_id="contrarian_momentum",
            display_name="Contrarian Momentum",
            primary_sectors=["all"],
            primary_strategy="momentum",
            risk_appetite=0.7,
            contrarian_factor=0.85,
            conviction_style=0.6,
            regime_sensitivity=0.35,
            lookback_days=20,
            holding_period="scalp",
            min_confidence=0.65,
            max_picks_per_scan=4,
            peer_group="contrarian_cluster",
        ),

        # =====================================================================
        # REGIME-AWARE (28-31)
        # =====================================================================
        AgentDNA(
            agent_id="regime_adaptive_bull",
            display_name="Regime Adaptive Bull",
            primary_sectors=["all"],
            primary_strategy="momentum",
            risk_appetite=0.7,
            contrarian_factor=0.1,
            conviction_style=0.6,
            regime_sensitivity=0.95,
            lookback_days=50,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="regime_cluster",
        ),
        AgentDNA(
            agent_id="regime_adaptive_bear",
            display_name="Regime Adaptive Bear",
            primary_sectors=["all"],
            primary_strategy="mean_reversion",
            risk_appetite=0.3,
            contrarian_factor=0.4,
            conviction_style=0.5,
            regime_sensitivity=0.95,
            lookback_days=30,
            holding_period="swing",
            min_confidence=0.65,
            max_picks_per_scan=4,
            peer_group="regime_cluster",
        ),
        AgentDNA(
            agent_id="regime_adaptive_vol",
            display_name="Regime Adaptive Volatility",
            primary_sectors=["all"],
            primary_strategy="volatility",
            risk_appetite=0.5,
            contrarian_factor=0.2,
            conviction_style=0.5,
            regime_sensitivity=0.9,
            lookback_days=20,
            holding_period="scalp",
            min_confidence=0.65,
            max_picks_per_scan=4,
            peer_group="regime_cluster",
        ),
        AgentDNA(
            agent_id="regime_adaptive_value",
            display_name="Regime Adaptive Value",
            primary_sectors=["all"],
            primary_strategy="value",
            risk_appetite=0.3,
            contrarian_factor=0.15,
            conviction_style=0.5,
            regime_sensitivity=0.85,
            lookback_days=120,
            holding_period="position",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="regime_cluster",
        ),

        # =====================================================================
        # HYBRID SECTOR+STRATEGY (32-61)
        # =====================================================================
        AgentDNA(
            agent_id="biotech_momentum",
            display_name="Biotech Momentum",
            primary_sectors=["biotech"],
            secondary_sectors=["healthcare"],
            primary_strategy="momentum",
            risk_appetite=0.7,
            contrarian_factor=0.15,
            conviction_style=0.6,
            regime_sensitivity=0.35,
            lookback_days=30,
            holding_period="swing",
            min_confidence=0.65,
            max_picks_per_scan=4,
            peer_group="healthcare_cluster",
        ),
        AgentDNA(
            agent_id="biotech_event",
            display_name="Biotech Event-Driven",
            primary_sectors=["biotech"],
            secondary_sectors=["healthcare", "pharma"],
            primary_strategy="event_driven",
            risk_appetite=0.7,
            contrarian_factor=0.1,
            conviction_style=0.7,
            regime_sensitivity=0.3,
            lookback_days=20,
            holding_period="scalp",
            min_confidence=0.7,
            max_picks_per_scan=3,
            peer_group="healthcare_cluster",
        ),
        AgentDNA(
            agent_id="fintech_growth",
            display_name="Fintech Growth",
            primary_sectors=["technology", "financials"],
            secondary_sectors=["cloud_saas"],
            primary_strategy="growth",
            risk_appetite=0.5,
            contrarian_factor=0.1,
            conviction_style=0.5,
            regime_sensitivity=0.3,
            lookback_days=60,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="tech_cluster",
        ),
        AgentDNA(
            agent_id="fintech_breakout",
            display_name="Fintech Breakout",
            primary_sectors=["technology", "financials"],
            secondary_sectors=[],
            primary_strategy="breakout",
            risk_appetite=0.7,
            contrarian_factor=0.15,
            conviction_style=0.6,
            regime_sensitivity=0.35,
            lookback_days=20,
            holding_period="scalp",
            min_confidence=0.65,
            max_picks_per_scan=4,
            peer_group="tech_cluster",
        ),
        AgentDNA(
            agent_id="oil_gas_mean_rev",
            display_name="Oil & Gas Mean Reversion",
            primary_sectors=["oil_gas"],
            secondary_sectors=["energy"],
            primary_strategy="mean_reversion",
            risk_appetite=0.5,
            contrarian_factor=0.3,
            conviction_style=0.5,
            regime_sensitivity=0.4,
            lookback_days=40,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="energy_cluster",
        ),
        AgentDNA(
            agent_id="oil_gas_momentum",
            display_name="Oil & Gas Momentum",
            primary_sectors=["oil_gas"],
            secondary_sectors=["energy"],
            primary_strategy="momentum",
            risk_appetite=0.7,
            contrarian_factor=0.15,
            conviction_style=0.6,
            regime_sensitivity=0.4,
            lookback_days=30,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="energy_cluster",
        ),
        AgentDNA(
            agent_id="renewable_growth",
            display_name="Renewable Energy Growth",
            primary_sectors=["renewables", "industrials"],
            secondary_sectors=["energy"],
            primary_strategy="growth",
            risk_appetite=0.5,
            contrarian_factor=0.1,
            conviction_style=0.5,
            regime_sensitivity=0.3,
            lookback_days=90,
            holding_period="position",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="energy_cluster",
        ),
        AgentDNA(
            agent_id="chip_momentum",
            display_name="Semiconductor Momentum",
            primary_sectors=["semiconductors"],
            secondary_sectors=["technology"],
            primary_strategy="momentum",
            risk_appetite=0.7,
            contrarian_factor=0.15,
            conviction_style=0.6,
            regime_sensitivity=0.4,
            lookback_days=40,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="tech_cluster",
        ),
        AgentDNA(
            agent_id="chip_mean_rev",
            display_name="Semiconductor Mean Reversion",
            primary_sectors=["semiconductors"],
            secondary_sectors=["technology"],
            primary_strategy="mean_reversion",
            risk_appetite=0.5,
            contrarian_factor=0.3,
            conviction_style=0.5,
            regime_sensitivity=0.35,
            lookback_days=30,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="tech_cluster",
        ),
        AgentDNA(
            agent_id="saas_growth",
            display_name="SaaS Growth",
            primary_sectors=["cloud_saas"],
            secondary_sectors=["technology"],
            primary_strategy="growth",
            risk_appetite=0.5,
            contrarian_factor=0.1,
            conviction_style=0.5,
            regime_sensitivity=0.3,
            lookback_days=60,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="tech_cluster",
        ),
        AgentDNA(
            agent_id="saas_value",
            display_name="SaaS Value",
            primary_sectors=["cloud_saas"],
            secondary_sectors=["technology"],
            primary_strategy="value",
            risk_appetite=0.3,
            contrarian_factor=0.2,
            conviction_style=0.5,
            regime_sensitivity=0.25,
            lookback_days=120,
            holding_period="position",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="tech_cluster",
        ),
        AgentDNA(
            agent_id="retail_sentiment",
            display_name="Retail Sentiment",
            primary_sectors=["retail"],
            secondary_sectors=["consumer_discretionary"],
            primary_strategy="sentiment",
            risk_appetite=0.5,
            contrarian_factor=0.2,
            conviction_style=0.5,
            regime_sensitivity=0.3,
            lookback_days=20,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="consumer_cluster",
        ),
        AgentDNA(
            agent_id="retail_mean_rev",
            display_name="Retail Mean Reversion",
            primary_sectors=["retail"],
            secondary_sectors=["consumer_discretionary"],
            primary_strategy="mean_reversion",
            risk_appetite=0.5,
            contrarian_factor=0.3,
            conviction_style=0.5,
            regime_sensitivity=0.3,
            lookback_days=40,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="consumer_cluster",
        ),
        AgentDNA(
            agent_id="pharma_value",
            display_name="Pharma Value",
            primary_sectors=["pharma"],
            secondary_sectors=["healthcare"],
            primary_strategy="value",
            risk_appetite=0.3,
            contrarian_factor=0.15,
            conviction_style=0.5,
            regime_sensitivity=0.2,
            lookback_days=120,
            holding_period="position",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="healthcare_cluster",
        ),
        AgentDNA(
            agent_id="pharma_event",
            display_name="Pharma Event-Driven",
            primary_sectors=["pharma"],
            secondary_sectors=["healthcare", "biotech"],
            primary_strategy="event_driven",
            risk_appetite=0.5,
            contrarian_factor=0.1,
            conviction_style=0.6,
            regime_sensitivity=0.3,
            lookback_days=30,
            holding_period="swing",
            min_confidence=0.65,
            max_picks_per_scan=4,
            peer_group="healthcare_cluster",
        ),
        AgentDNA(
            agent_id="bank_value",
            display_name="Bank Value",
            primary_sectors=["banks"],
            secondary_sectors=["financials"],
            primary_strategy="value",
            risk_appetite=0.3,
            contrarian_factor=0.2,
            conviction_style=0.5,
            regime_sensitivity=0.25,
            lookback_days=200,
            holding_period="position",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="financials_cluster",
        ),
        AgentDNA(
            agent_id="bank_momentum",
            display_name="Bank Momentum",
            primary_sectors=["banks"],
            secondary_sectors=["financials"],
            primary_strategy="momentum",
            risk_appetite=0.5,
            contrarian_factor=0.15,
            conviction_style=0.5,
            regime_sensitivity=0.3,
            lookback_days=50,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="financials_cluster",
        ),
        AgentDNA(
            agent_id="insurance_value",
            display_name="Insurance Value",
            primary_sectors=["insurance"],
            secondary_sectors=["financials"],
            primary_strategy="value",
            risk_appetite=0.3,
            contrarian_factor=0.15,
            conviction_style=0.4,
            regime_sensitivity=0.2,
            lookback_days=200,
            holding_period="position",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="financials_cluster",
        ),
        AgentDNA(
            agent_id="defense_momentum",
            display_name="Defense Momentum",
            primary_sectors=["defense"],
            secondary_sectors=["industrials", "aerospace"],
            primary_strategy="momentum",
            risk_appetite=0.5,
            contrarian_factor=0.1,
            conviction_style=0.5,
            regime_sensitivity=0.3,
            lookback_days=50,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="industrials_cluster",
        ),
        AgentDNA(
            agent_id="mining_breakout",
            display_name="Mining Breakout",
            primary_sectors=["mining"],
            secondary_sectors=["materials"],
            primary_strategy="breakout",
            risk_appetite=0.7,
            contrarian_factor=0.2,
            conviction_style=0.6,
            regime_sensitivity=0.4,
            lookback_days=20,
            holding_period="scalp",
            min_confidence=0.65,
            max_picks_per_scan=4,
            peer_group="materials_cluster",
        ),
        AgentDNA(
            agent_id="mining_mean_rev",
            display_name="Mining Mean Reversion",
            primary_sectors=["mining"],
            secondary_sectors=["materials"],
            primary_strategy="mean_reversion",
            risk_appetite=0.5,
            contrarian_factor=0.3,
            conviction_style=0.5,
            regime_sensitivity=0.35,
            lookback_days=40,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="materials_cluster",
        ),
        AgentDNA(
            agent_id="reit_value",
            display_name="REIT Value",
            primary_sectors=["reits"],
            secondary_sectors=["real_estate"],
            primary_strategy="value",
            risk_appetite=0.3,
            contrarian_factor=0.15,
            conviction_style=0.4,
            regime_sensitivity=0.25,
            lookback_days=120,
            holding_period="position",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="real_estate_cluster",
        ),
        AgentDNA(
            agent_id="media_sentiment",
            display_name="Media Sentiment",
            primary_sectors=["media"],
            secondary_sectors=["communication_services"],
            primary_strategy="sentiment",
            risk_appetite=0.5,
            contrarian_factor=0.2,
            conviction_style=0.5,
            regime_sensitivity=0.3,
            lookback_days=20,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="comms_cluster",
        ),
        AgentDNA(
            agent_id="telecom_value",
            display_name="Telecom Value",
            primary_sectors=["telecom"],
            secondary_sectors=["communication_services"],
            primary_strategy="value",
            risk_appetite=0.3,
            contrarian_factor=0.15,
            conviction_style=0.4,
            regime_sensitivity=0.2,
            lookback_days=120,
            holding_period="position",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="comms_cluster",
        ),
        AgentDNA(
            agent_id="food_bev_value",
            display_name="Food & Beverage Value",
            primary_sectors=["food_beverage"],
            secondary_sectors=["consumer_staples"],
            primary_strategy="value",
            risk_appetite=0.3,
            contrarian_factor=0.1,
            conviction_style=0.4,
            regime_sensitivity=0.2,
            lookback_days=200,
            holding_period="position",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="consumer_cluster",
        ),
        AgentDNA(
            agent_id="auto_momentum",
            display_name="Auto Momentum",
            primary_sectors=["auto"],
            secondary_sectors=["consumer_discretionary"],
            primary_strategy="momentum",
            risk_appetite=0.5,
            contrarian_factor=0.15,
            conviction_style=0.5,
            regime_sensitivity=0.35,
            lookback_days=50,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="consumer_cluster",
        ),
        AgentDNA(
            agent_id="construction_growth",
            display_name="Construction Growth",
            primary_sectors=["construction"],
            secondary_sectors=["industrials", "materials"],
            primary_strategy="growth",
            risk_appetite=0.5,
            contrarian_factor=0.1,
            conviction_style=0.5,
            regime_sensitivity=0.3,
            lookback_days=60,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="industrials_cluster",
        ),
        AgentDNA(
            agent_id="aerospace_momentum",
            display_name="Aerospace Momentum",
            primary_sectors=["aerospace"],
            secondary_sectors=["industrials", "defense"],
            primary_strategy="momentum",
            risk_appetite=0.5,
            contrarian_factor=0.1,
            conviction_style=0.5,
            regime_sensitivity=0.3,
            lookback_days=50,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="industrials_cluster",
        ),
        AgentDNA(
            agent_id="gaming_sentiment",
            display_name="Gaming Sentiment",
            primary_sectors=["gaming"],
            secondary_sectors=["communication_services", "media"],
            primary_strategy="sentiment",
            secondary_strategy="event_driven",
            risk_appetite=0.7,
            contrarian_factor=0.2,
            conviction_style=0.6,
            regime_sensitivity=0.35,
            lookback_days=20,
            holding_period="scalp",
            min_confidence=0.65,
            max_picks_per_scan=4,
            peer_group="comms_cluster",
        ),
        AgentDNA(
            agent_id="cyber_security_growth",
            display_name="Cybersecurity Growth",
            primary_sectors=["cyber_security"],
            secondary_sectors=["technology"],
            primary_strategy="growth",
            risk_appetite=0.5,
            contrarian_factor=0.1,
            conviction_style=0.5,
            regime_sensitivity=0.3,
            lookback_days=60,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="tech_cluster",
        ),

        # =====================================================================
        # AGGRESSIVE HIGH-CONVICTION (62-66)
        # =====================================================================
        AgentDNA(
            agent_id="sniper_tech",
            display_name="Sniper Tech",
            primary_sectors=["technology"],
            secondary_sectors=["semiconductors", "cloud_saas", "cyber_security"],
            primary_strategy="momentum",
            risk_appetite=0.8,
            contrarian_factor=0.1,
            conviction_style=0.9,
            regime_sensitivity=0.4,
            lookback_days=30,
            holding_period="swing",
            min_confidence=0.85,
            max_picks_per_scan=2,
            peer_group="sniper_cluster",
        ),
        AgentDNA(
            agent_id="sniper_healthcare",
            display_name="Sniper Healthcare",
            primary_sectors=["healthcare"],
            secondary_sectors=["biotech", "pharma"],
            primary_strategy="event_driven",
            risk_appetite=0.8,
            contrarian_factor=0.1,
            conviction_style=0.9,
            regime_sensitivity=0.35,
            lookback_days=20,
            holding_period="scalp",
            min_confidence=0.85,
            max_picks_per_scan=2,
            peer_group="sniper_cluster",
        ),
        AgentDNA(
            agent_id="sniper_energy",
            display_name="Sniper Energy",
            primary_sectors=["energy"],
            secondary_sectors=["oil_gas", "renewables"],
            primary_strategy="breakout",
            risk_appetite=0.8,
            contrarian_factor=0.15,
            conviction_style=0.9,
            regime_sensitivity=0.4,
            lookback_days=20,
            holding_period="scalp",
            min_confidence=0.9,
            max_picks_per_scan=1,
            peer_group="sniper_cluster",
        ),
        AgentDNA(
            agent_id="sniper_financial",
            display_name="Sniper Financial",
            primary_sectors=["financials"],
            secondary_sectors=["banks", "insurance"],
            primary_strategy="value",
            risk_appetite=0.5,
            contrarian_factor=0.15,
            conviction_style=0.9,
            regime_sensitivity=0.3,
            lookback_days=120,
            holding_period="position",
            min_confidence=0.85,
            max_picks_per_scan=2,
            peer_group="sniper_cluster",
        ),
        AgentDNA(
            agent_id="sniper_broad",
            display_name="Sniper Broad Market",
            primary_sectors=["all"],
            primary_strategy="momentum",
            risk_appetite=0.8,
            contrarian_factor=0.1,
            conviction_style=0.95,
            regime_sensitivity=0.45,
            lookback_days=40,
            holding_period="swing",
            min_confidence=0.9,
            max_picks_per_scan=1,
            peer_group="sniper_cluster",
        ),

        # =====================================================================
        # CONSERVATIVE GUARDIANS (67-71)
        # =====================================================================
        AgentDNA(
            agent_id="guardian_value",
            display_name="Guardian Value",
            primary_sectors=["all"],
            primary_strategy="value",
            risk_appetite=0.1,
            contrarian_factor=0.1,
            conviction_style=0.2,
            regime_sensitivity=0.2,
            lookback_days=200,
            holding_period="position",
            min_confidence=0.6,
            max_picks_per_scan=8,
            peer_group="guardian_cluster",
        ),
        AgentDNA(
            agent_id="guardian_stable",
            display_name="Guardian Stable Sectors",
            primary_sectors=["utilities", "consumer_staples", "healthcare"],
            primary_strategy="value",
            risk_appetite=0.1,
            contrarian_factor=0.05,
            conviction_style=0.3,
            regime_sensitivity=0.15,
            lookback_days=200,
            holding_period="position",
            min_confidence=0.6,
            max_picks_per_scan=6,
            peer_group="guardian_cluster",
        ),
        AgentDNA(
            agent_id="guardian_dividend",
            display_name="Guardian Dividend",
            primary_sectors=["financials", "utilities", "consumer_staples"],
            primary_strategy="value",
            risk_appetite=0.15,
            contrarian_factor=0.05,
            conviction_style=0.3,
            regime_sensitivity=0.15,
            lookback_days=252,
            holding_period="macro",
            min_confidence=0.6,
            max_picks_per_scan=6,
            peer_group="guardian_cluster",
        ),
        AgentDNA(
            agent_id="guardian_quality",
            display_name="Guardian Quality Growth",
            primary_sectors=["all"],
            primary_strategy="growth",
            secondary_strategy="value",
            risk_appetite=0.2,
            contrarian_factor=0.1,
            conviction_style=0.4,
            regime_sensitivity=0.25,
            lookback_days=120,
            holding_period="position",
            min_confidence=0.65,
            max_picks_per_scan=5,
            peer_group="guardian_cluster",
        ),
        AgentDNA(
            agent_id="guardian_defensive",
            display_name="Guardian Defensive",
            primary_sectors=["all"],
            primary_strategy="mean_reversion",
            risk_appetite=0.15,
            contrarian_factor=0.2,
            conviction_style=0.3,
            regime_sensitivity=0.3,
            lookback_days=60,
            holding_period="swing",
            min_confidence=0.65,
            max_picks_per_scan=5,
            peer_group="guardian_cluster",
        ),

        # =====================================================================
        # VOLUME/FLOW SPECIALISTS (72-75)
        # =====================================================================
        AgentDNA(
            agent_id="volume_surge",
            display_name="Volume Surge Detector",
            primary_sectors=["all"],
            primary_strategy="event_driven",
            risk_appetite=0.5,
            contrarian_factor=0.1,
            conviction_style=0.6,
            regime_sensitivity=0.3,
            lookback_days=10,
            holding_period="scalp",
            min_confidence=0.65,
            max_picks_per_scan=5,
            peer_group="flow_cluster",
        ),
        AgentDNA(
            agent_id="volume_dry_up",
            display_name="Volume Dry-Up Detector",
            primary_sectors=["all"],
            primary_strategy="volatility",
            risk_appetite=0.5,
            contrarian_factor=0.3,
            conviction_style=0.5,
            regime_sensitivity=0.4,
            lookback_days=30,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="flow_cluster",
        ),
        AgentDNA(
            agent_id="accumulation_watcher",
            display_name="Accumulation Watcher",
            primary_sectors=["all"],
            primary_strategy="value",
            risk_appetite=0.5,
            contrarian_factor=0.2,
            conviction_style=0.5,
            regime_sensitivity=0.3,
            lookback_days=60,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="flow_cluster",
        ),
        AgentDNA(
            agent_id="distribution_watcher",
            display_name="Distribution Watcher",
            primary_sectors=["all"],
            primary_strategy="momentum",
            risk_appetite=0.5,
            contrarian_factor=0.3,
            conviction_style=0.5,
            regime_sensitivity=0.3,
            lookback_days=40,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="flow_cluster",
        ),

        # =====================================================================
        # WILD CARD (76-80)
        # =====================================================================
        AgentDNA(
            agent_id="random_walk",
            display_name="Random Walk Theorist",
            primary_sectors=["all"],
            primary_strategy="momentum",
            risk_appetite=0.5,
            contrarian_factor=0.5,
            conviction_style=0.5,
            regime_sensitivity=0.3,
            lookback_days=20,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="wildcard_cluster",
        ),
        AgentDNA(
            agent_id="anti_momentum",
            display_name="Anti-Momentum",
            primary_sectors=["all"],
            primary_strategy="momentum",
            risk_appetite=0.5,
            contrarian_factor=1.0,
            conviction_style=0.5,
            regime_sensitivity=0.3,
            lookback_days=50,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="wildcard_cluster",
        ),
        AgentDNA(
            agent_id="patience_extreme",
            display_name="Extreme Patience",
            primary_sectors=["all"],
            primary_strategy="value",
            risk_appetite=0.05,
            contrarian_factor=0.2,
            conviction_style=0.8,
            regime_sensitivity=0.1,
            lookback_days=252,
            holding_period="macro",
            min_confidence=0.95,
            max_picks_per_scan=1,
            peer_group="wildcard_cluster",
        ),
        AgentDNA(
            agent_id="sector_rotation",
            display_name="Sector Rotation",
            primary_sectors=["all"],
            primary_strategy="momentum",
            risk_appetite=0.5,
            contrarian_factor=0.15,
            conviction_style=0.5,
            regime_sensitivity=0.6,
            lookback_days=30,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="wildcard_cluster",
        ),
        AgentDNA(
            agent_id="gap_hunter",
            display_name="Gap Hunter",
            primary_sectors=["all"],
            primary_strategy="event_driven",
            risk_appetite=0.8,
            contrarian_factor=0.2,
            conviction_style=0.7,
            regime_sensitivity=0.3,
            lookback_days=5,
            holding_period="scalp",
            min_confidence=0.7,
            max_picks_per_scan=3,
            peer_group="wildcard_cluster",
        ),

        # =====================================================================
        # NEW OVERLAPPING AGENTS — TECH DEPTH (81-86)
        # =====================================================================
        AgentDNA(
            agent_id="tech_value",
            display_name="Tech Value",
            primary_sectors=["technology"],
            secondary_sectors=["cloud_saas", "semiconductors"],
            primary_strategy="value",
            risk_appetite=0.3,
            contrarian_factor=0.2,
            conviction_style=0.5,
            regime_sensitivity=0.25,
            lookback_days=120,
            holding_period="position",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="tech_cluster",
        ),
        AgentDNA(
            agent_id="tech_breakout",
            display_name="Tech Breakout",
            primary_sectors=["technology"],
            secondary_sectors=["semiconductors", "cloud_saas"],
            primary_strategy="breakout",
            risk_appetite=0.7,
            contrarian_factor=0.15,
            conviction_style=0.6,
            regime_sensitivity=0.4,
            lookback_days=20,
            holding_period="scalp",
            min_confidence=0.65,
            max_picks_per_scan=4,
            peer_group="tech_cluster",
        ),
        AgentDNA(
            agent_id="tech_mean_rev",
            display_name="Tech Mean Reversion",
            primary_sectors=["technology"],
            secondary_sectors=["semiconductors", "cloud_saas"],
            primary_strategy="mean_reversion",
            risk_appetite=0.5,
            contrarian_factor=0.3,
            conviction_style=0.5,
            regime_sensitivity=0.3,
            lookback_days=40,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="tech_cluster",
        ),
        AgentDNA(
            agent_id="tech_sentiment",
            display_name="Tech Sentiment",
            primary_sectors=["technology"],
            secondary_sectors=["cloud_saas", "cyber_security"],
            primary_strategy="sentiment",
            risk_appetite=0.5,
            contrarian_factor=0.2,
            conviction_style=0.5,
            regime_sensitivity=0.35,
            lookback_days=20,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="tech_cluster",
        ),
        AgentDNA(
            agent_id="chip_breakout",
            display_name="Semiconductor Breakout",
            primary_sectors=["semiconductors"],
            secondary_sectors=["technology"],
            primary_strategy="breakout",
            risk_appetite=0.7,
            contrarian_factor=0.15,
            conviction_style=0.6,
            regime_sensitivity=0.4,
            lookback_days=20,
            holding_period="scalp",
            min_confidence=0.65,
            max_picks_per_scan=4,
            peer_group="tech_cluster",
        ),
        AgentDNA(
            agent_id="saas_momentum",
            display_name="SaaS Momentum",
            primary_sectors=["cloud_saas"],
            secondary_sectors=["technology"],
            primary_strategy="momentum",
            risk_appetite=0.6,
            contrarian_factor=0.15,
            conviction_style=0.55,
            regime_sensitivity=0.35,
            lookback_days=40,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="tech_cluster",
        ),

        # =====================================================================
        # NEW OVERLAPPING AGENTS — HEALTHCARE DEPTH (87-91)
        # =====================================================================
        AgentDNA(
            agent_id="healthcare_value",
            display_name="Healthcare Value",
            primary_sectors=["healthcare"],
            secondary_sectors=["pharma", "biotech"],
            primary_strategy="value",
            risk_appetite=0.3,
            contrarian_factor=0.15,
            conviction_style=0.5,
            regime_sensitivity=0.2,
            lookback_days=120,
            holding_period="position",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="healthcare_cluster",
        ),
        AgentDNA(
            agent_id="healthcare_momentum",
            display_name="Healthcare Momentum",
            primary_sectors=["healthcare"],
            secondary_sectors=["biotech", "pharma"],
            primary_strategy="momentum",
            risk_appetite=0.5,
            contrarian_factor=0.15,
            conviction_style=0.5,
            regime_sensitivity=0.35,
            lookback_days=50,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="healthcare_cluster",
        ),
        AgentDNA(
            agent_id="biotech_breakout",
            display_name="Biotech Breakout",
            primary_sectors=["biotech"],
            secondary_sectors=["healthcare"],
            primary_strategy="breakout",
            risk_appetite=0.8,
            contrarian_factor=0.15,
            conviction_style=0.7,
            regime_sensitivity=0.35,
            lookback_days=15,
            holding_period="scalp",
            min_confidence=0.7,
            max_picks_per_scan=3,
            peer_group="healthcare_cluster",
        ),
        AgentDNA(
            agent_id="pharma_momentum",
            display_name="Pharma Momentum",
            primary_sectors=["pharma"],
            secondary_sectors=["healthcare"],
            primary_strategy="momentum",
            risk_appetite=0.5,
            contrarian_factor=0.15,
            conviction_style=0.5,
            regime_sensitivity=0.3,
            lookback_days=50,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="healthcare_cluster",
        ),
        AgentDNA(
            agent_id="healthcare_sentiment",
            display_name="Healthcare Sentiment",
            primary_sectors=["healthcare"],
            secondary_sectors=["biotech", "pharma"],
            primary_strategy="sentiment",
            risk_appetite=0.5,
            contrarian_factor=0.2,
            conviction_style=0.5,
            regime_sensitivity=0.3,
            lookback_days=20,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="healthcare_cluster",
        ),

        # =====================================================================
        # NEW OVERLAPPING AGENTS — FINANCIALS DEPTH (92-95)
        # =====================================================================
        AgentDNA(
            agent_id="financial_momentum",
            display_name="Financial Momentum",
            primary_sectors=["financials"],
            secondary_sectors=["banks", "insurance"],
            primary_strategy="momentum",
            risk_appetite=0.5,
            contrarian_factor=0.15,
            conviction_style=0.5,
            regime_sensitivity=0.35,
            lookback_days=50,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="financials_cluster",
        ),
        AgentDNA(
            agent_id="financial_breakout",
            display_name="Financial Breakout",
            primary_sectors=["financials"],
            secondary_sectors=["banks"],
            primary_strategy="breakout",
            risk_appetite=0.6,
            contrarian_factor=0.15,
            conviction_style=0.6,
            regime_sensitivity=0.35,
            lookback_days=20,
            holding_period="scalp",
            min_confidence=0.65,
            max_picks_per_scan=4,
            peer_group="financials_cluster",
        ),
        AgentDNA(
            agent_id="bank_mean_rev",
            display_name="Bank Mean Reversion",
            primary_sectors=["banks"],
            secondary_sectors=["financials"],
            primary_strategy="mean_reversion",
            risk_appetite=0.4,
            contrarian_factor=0.3,
            conviction_style=0.5,
            regime_sensitivity=0.3,
            lookback_days=40,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="financials_cluster",
        ),
        AgentDNA(
            agent_id="insurance_momentum",
            display_name="Insurance Momentum",
            primary_sectors=["insurance"],
            secondary_sectors=["financials"],
            primary_strategy="momentum",
            risk_appetite=0.5,
            contrarian_factor=0.15,
            conviction_style=0.5,
            regime_sensitivity=0.3,
            lookback_days=50,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="financials_cluster",
        ),

        # =====================================================================
        # NEW OVERLAPPING AGENTS — ENERGY DEPTH (96-99)
        # =====================================================================
        AgentDNA(
            agent_id="energy_breakout",
            display_name="Energy Breakout",
            primary_sectors=["energy"],
            secondary_sectors=["oil_gas"],
            primary_strategy="breakout",
            risk_appetite=0.7,
            contrarian_factor=0.2,
            conviction_style=0.6,
            regime_sensitivity=0.4,
            lookback_days=20,
            holding_period="scalp",
            min_confidence=0.65,
            max_picks_per_scan=4,
            peer_group="energy_cluster",
        ),
        AgentDNA(
            agent_id="energy_momentum",
            display_name="Energy Momentum",
            primary_sectors=["energy"],
            secondary_sectors=["oil_gas", "renewables"],
            primary_strategy="momentum",
            risk_appetite=0.6,
            contrarian_factor=0.15,
            conviction_style=0.55,
            regime_sensitivity=0.4,
            lookback_days=40,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="energy_cluster",
        ),
        AgentDNA(
            agent_id="renewable_breakout",
            display_name="Renewable Breakout",
            primary_sectors=["renewables"],
            secondary_sectors=["energy"],
            primary_strategy="breakout",
            risk_appetite=0.7,
            contrarian_factor=0.15,
            conviction_style=0.6,
            regime_sensitivity=0.35,
            lookback_days=20,
            holding_period="scalp",
            min_confidence=0.65,
            max_picks_per_scan=4,
            peer_group="energy_cluster",
        ),
        AgentDNA(
            agent_id="oil_gas_value",
            display_name="Oil & Gas Value",
            primary_sectors=["oil_gas"],
            secondary_sectors=["energy"],
            primary_strategy="value",
            risk_appetite=0.3,
            contrarian_factor=0.2,
            conviction_style=0.5,
            regime_sensitivity=0.3,
            lookback_days=120,
            holding_period="position",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="energy_cluster",
        ),

        # =====================================================================
        # NEW OVERLAPPING AGENTS — CROSS-SECTOR MOMENTUM (100-104)
        # =====================================================================
        AgentDNA(
            agent_id="aggressive_momentum",
            display_name="Aggressive Momentum",
            primary_sectors=["all"],
            primary_strategy="momentum",
            risk_appetite=0.8,
            contrarian_factor=0.05,
            conviction_style=0.7,
            regime_sensitivity=0.4,
            lookback_days=30,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="momentum_cluster",
        ),
        AgentDNA(
            agent_id="conservative_momentum",
            display_name="Conservative Momentum",
            primary_sectors=["all"],
            primary_strategy="momentum",
            risk_appetite=0.2,
            contrarian_factor=0.1,
            conviction_style=0.4,
            regime_sensitivity=0.25,
            lookback_days=60,
            holding_period="swing",
            min_confidence=0.7,
            max_picks_per_scan=4,
            peer_group="momentum_cluster",
        ),
        AgentDNA(
            agent_id="short_momentum",
            display_name="Short-Term Momentum",
            primary_sectors=["all"],
            primary_strategy="momentum",
            risk_appetite=0.6,
            contrarian_factor=0.1,
            conviction_style=0.6,
            regime_sensitivity=0.35,
            lookback_days=15,
            holding_period="scalp",
            min_confidence=0.65,
            max_picks_per_scan=5,
            peer_group="momentum_cluster",
        ),
        AgentDNA(
            agent_id="long_momentum",
            display_name="Long-Term Momentum",
            primary_sectors=["all"],
            primary_strategy="momentum",
            risk_appetite=0.4,
            contrarian_factor=0.1,
            conviction_style=0.5,
            regime_sensitivity=0.25,
            lookback_days=120,
            holding_period="position",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="momentum_cluster",
        ),
        AgentDNA(
            agent_id="vol_filtered_momentum",
            display_name="Volatility-Filtered Momentum",
            primary_sectors=["all"],
            primary_strategy="momentum",
            secondary_strategy="volatility",
            risk_appetite=0.5,
            contrarian_factor=0.15,
            conviction_style=0.5,
            regime_sensitivity=0.45,
            lookback_days=40,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="momentum_cluster",
        ),

        # =====================================================================
        # NEW OVERLAPPING AGENTS — CROSS-SECTOR VALUE (105-108)
        # =====================================================================
        AgentDNA(
            agent_id="deep_value",
            display_name="Deep Value",
            primary_sectors=["all"],
            primary_strategy="value",
            risk_appetite=0.2,
            contrarian_factor=0.4,
            conviction_style=0.8,
            regime_sensitivity=0.15,
            lookback_days=252,
            holding_period="macro",
            min_confidence=0.7,
            max_picks_per_scan=3,
            peer_group="value_cluster",
        ),
        AgentDNA(
            agent_id="relative_value",
            display_name="Relative Value",
            primary_sectors=["all"],
            primary_strategy="value",
            secondary_strategy="mean_reversion",
            risk_appetite=0.4,
            contrarian_factor=0.25,
            conviction_style=0.5,
            regime_sensitivity=0.3,
            lookback_days=120,
            holding_period="position",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="value_cluster",
        ),
        AgentDNA(
            agent_id="quality_value",
            display_name="Quality Value",
            primary_sectors=["all"],
            primary_strategy="value",
            secondary_strategy="growth",
            risk_appetite=0.3,
            contrarian_factor=0.15,
            conviction_style=0.5,
            regime_sensitivity=0.2,
            lookback_days=200,
            holding_period="position",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="value_cluster",
        ),
        AgentDNA(
            agent_id="momentum_value",
            display_name="Momentum Value",
            primary_sectors=["all"],
            primary_strategy="value",
            secondary_strategy="momentum",
            risk_appetite=0.5,
            contrarian_factor=0.15,
            conviction_style=0.5,
            regime_sensitivity=0.3,
            lookback_days=90,
            holding_period="position",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="value_cluster",
        ),

        # =====================================================================
        # NEW OVERLAPPING AGENTS — CROSS-SECTOR MEAN REVERSION (109-112)
        # =====================================================================
        AgentDNA(
            agent_id="aggressive_mean_rev",
            display_name="Aggressive Mean Reversion",
            primary_sectors=["all"],
            primary_strategy="mean_reversion",
            risk_appetite=0.7,
            contrarian_factor=0.4,
            conviction_style=0.6,
            regime_sensitivity=0.35,
            lookback_days=20,
            holding_period="scalp",
            min_confidence=0.65,
            max_picks_per_scan=5,
            peer_group="mean_rev_cluster",
        ),
        AgentDNA(
            agent_id="conservative_mean_rev",
            display_name="Conservative Mean Reversion",
            primary_sectors=["all"],
            primary_strategy="mean_reversion",
            risk_appetite=0.2,
            contrarian_factor=0.25,
            conviction_style=0.4,
            regime_sensitivity=0.2,
            lookback_days=60,
            holding_period="swing",
            min_confidence=0.65,
            max_picks_per_scan=4,
            peer_group="mean_rev_cluster",
        ),
        AgentDNA(
            agent_id="vol_mean_rev",
            display_name="Volatility Mean Reversion",
            primary_sectors=["all"],
            primary_strategy="mean_reversion",
            secondary_strategy="volatility",
            risk_appetite=0.5,
            contrarian_factor=0.3,
            conviction_style=0.5,
            regime_sensitivity=0.4,
            lookback_days=30,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="mean_rev_cluster",
        ),
        AgentDNA(
            agent_id="sentiment_mean_rev",
            display_name="Sentiment Mean Reversion",
            primary_sectors=["all"],
            primary_strategy="mean_reversion",
            secondary_strategy="sentiment",
            risk_appetite=0.5,
            contrarian_factor=0.35,
            conviction_style=0.5,
            regime_sensitivity=0.3,
            lookback_days=30,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="mean_rev_cluster",
        ),

        # =====================================================================
        # NEW OVERLAPPING AGENTS — CONSUMER DEPTH (113-116)
        # =====================================================================
        AgentDNA(
            agent_id="consumer_disc_momentum",
            display_name="Consumer Discretionary Momentum",
            primary_sectors=["consumer_discretionary"],
            secondary_sectors=["retail", "auto"],
            primary_strategy="momentum",
            risk_appetite=0.6,
            contrarian_factor=0.15,
            conviction_style=0.5,
            regime_sensitivity=0.35,
            lookback_days=40,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="consumer_cluster",
        ),
        AgentDNA(
            agent_id="consumer_disc_breakout",
            display_name="Consumer Discretionary Breakout",
            primary_sectors=["consumer_discretionary"],
            secondary_sectors=["retail"],
            primary_strategy="breakout",
            risk_appetite=0.7,
            contrarian_factor=0.15,
            conviction_style=0.6,
            regime_sensitivity=0.35,
            lookback_days=20,
            holding_period="scalp",
            min_confidence=0.65,
            max_picks_per_scan=4,
            peer_group="consumer_cluster",
        ),
        AgentDNA(
            agent_id="consumer_staples_momentum",
            display_name="Consumer Staples Momentum",
            primary_sectors=["consumer_staples"],
            secondary_sectors=["food_beverage"],
            primary_strategy="momentum",
            risk_appetite=0.3,
            contrarian_factor=0.1,
            conviction_style=0.4,
            regime_sensitivity=0.25,
            lookback_days=60,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="consumer_cluster",
        ),
        AgentDNA(
            agent_id="retail_breakout",
            display_name="Retail Breakout",
            primary_sectors=["retail"],
            secondary_sectors=["consumer_discretionary"],
            primary_strategy="breakout",
            risk_appetite=0.7,
            contrarian_factor=0.15,
            conviction_style=0.6,
            regime_sensitivity=0.35,
            lookback_days=20,
            holding_period="scalp",
            min_confidence=0.65,
            max_picks_per_scan=4,
            peer_group="consumer_cluster",
        ),

        # =====================================================================
        # NEW OVERLAPPING AGENTS — INDUSTRIALS DEPTH (117-119)
        # =====================================================================
        AgentDNA(
            agent_id="industrial_value",
            display_name="Industrial Value",
            primary_sectors=["industrials"],
            secondary_sectors=["defense", "aerospace", "construction"],
            primary_strategy="value",
            risk_appetite=0.3,
            contrarian_factor=0.15,
            conviction_style=0.5,
            regime_sensitivity=0.25,
            lookback_days=120,
            holding_period="position",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="industrials_cluster",
        ),
        AgentDNA(
            agent_id="defense_value",
            display_name="Defense Value",
            primary_sectors=["defense"],
            secondary_sectors=["industrials", "aerospace"],
            primary_strategy="value",
            risk_appetite=0.3,
            contrarian_factor=0.15,
            conviction_style=0.5,
            regime_sensitivity=0.2,
            lookback_days=120,
            holding_period="position",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="industrials_cluster",
        ),
        AgentDNA(
            agent_id="aerospace_breakout",
            display_name="Aerospace Breakout",
            primary_sectors=["aerospace"],
            secondary_sectors=["industrials", "defense"],
            primary_strategy="breakout",
            risk_appetite=0.7,
            contrarian_factor=0.15,
            conviction_style=0.6,
            regime_sensitivity=0.35,
            lookback_days=20,
            holding_period="scalp",
            min_confidence=0.65,
            max_picks_per_scan=4,
            peer_group="industrials_cluster",
        ),

        # =====================================================================
        # NEW OVERLAPPING AGENTS — MULTI-STRATEGY BLENDERS (120-121)
        # =====================================================================
        AgentDNA(
            agent_id="momentum_value_blend",
            display_name="Momentum-Value Blend",
            primary_sectors=["all"],
            primary_strategy="momentum",
            secondary_strategy="value",
            risk_appetite=0.4,
            contrarian_factor=0.15,
            conviction_style=0.5,
            regime_sensitivity=0.3,
            lookback_days=90,
            holding_period="position",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="blender_cluster",
        ),
        AgentDNA(
            agent_id="growth_momentum_blend",
            display_name="Growth-Momentum Blend",
            primary_sectors=["all"],
            primary_strategy="growth",
            secondary_strategy="momentum",
            risk_appetite=0.6,
            contrarian_factor=0.1,
            conviction_style=0.55,
            regime_sensitivity=0.35,
            lookback_days=60,
            holding_period="swing",
            min_confidence=0.6,
            max_picks_per_scan=5,
            peer_group="blender_cluster",
        ),
    ]

    return agents


# Module-level list of all agents, built once at import time.
ALL_AGENTS: List[AgentDNA] = build_all_agents()

# Lookup indexes for fast access.
_AGENT_BY_ID = {a.agent_id: a for a in ALL_AGENTS}
_AGENTS_BY_PEER_GROUP: dict = {}
for _agent in ALL_AGENTS:
    _AGENTS_BY_PEER_GROUP.setdefault(_agent.peer_group, []).append(_agent)


def get_agent_by_id(agent_id: str) -> Optional[AgentDNA]:
    """Return the AgentDNA for a given agent_id, or None if not found.

    Args:
        agent_id: Unique identifier string for the agent.

    Returns:
        The matching AgentDNA instance, or None.
    """
    return _AGENT_BY_ID.get(agent_id)


def get_agents_by_peer_group(group: str) -> List[AgentDNA]:
    """Return all agents belonging to a given peer group.

    Args:
        group: The peer_group cluster name.

    Returns:
        List of AgentDNA instances in that peer group (empty list if none).
    """
    return _AGENTS_BY_PEER_GROUP.get(group, [])


def get_all_peer_groups() -> Dict[str, int]:
    """Get all peer groups and their member counts."""
    return {g: len(agents) for g, agents in _AGENTS_BY_PEER_GROUP.items()}
