"""Enhanced Proposal — rich trade proposal for multi-stage pipeline."""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Dict, List, Optional
from enum import Enum


class InvestmentType(str, Enum):
    """All possible investment vehicle types."""
    INTRADAY = "intraday"
    SWING_TRADE = "swing_trade"
    POSITION_TRADE = "position_trade"
    LONG_TERM_INVESTMENT = "long_term_investment"
    SHARES_SPOT = "shares_spot"
    CALL_OPTION = "call_option"
    PUT_OPTION = "put_option"
    CALL_SPREAD = "call_spread"
    PUT_SPREAD = "put_spread"
    COVERED_CALL = "covered_call"
    PROTECTIVE_PUT = "protective_put"
    LEAPS = "leaps"
    PAIRS_TRADE = "pairs_trade"
    VOLATILITY_TRADE = "volatility_trade"
    NO_TRADE = "no_trade"


class ThesisType(str, Enum):
    """Classification of the thesis behind a proposal."""
    TECHNICAL = "technical"
    EVENT_DRIVEN = "event_driven"
    MACRO = "macro"
    VALUATION = "valuation"
    STRUCTURAL = "structural"
    MOMENTUM = "momentum"
    MEAN_REVERSION = "mean_reversion"
    SENTIMENT = "sentiment"
    VOLATILITY = "volatility"


@dataclass
class ProposalRisks:
    """Structured risk assessment for a proposal."""
    key_risks: List[str] = field(default_factory=list)
    invalidation_criteria: List[str] = field(default_factory=list)
    max_loss_pct: float = 0.0
    correlation_risk: str = ""
    execution_risk: str = "low"  # low | medium | high
    tail_risk: str = "low"
    crowded_trade_score: float = 0.0  # 0=uncrowded, 1=very crowded
    macro_contradiction: str = ""


@dataclass
class VehicleCandidate:
    """A candidate implementation for expressing a trade thesis."""
    vehicle_type: InvestmentType
    description: str
    expected_return: float
    expected_risk: float       # annualized vol or max loss
    payoff_asymmetry: float    # ratio of upside/downside
    timing_sensitivity: float  # 0=forgiving, 1=must be precise
    volatility_sensitivity: float  # 0=none, 1=highly vol-dependent
    liquidity_quality: float   # 0=illiquid, 1=very liquid
    implementation_simplicity: float  # 0=complex, 1=simple
    robustness_to_error: float  # 0=fragile, 1=robust to being early/wrong
    theta_decay_cost: float    # annualized cost of time decay (0 for shares)
    transaction_cost_bps: float
    composite_score: float = 0.0  # computed by vehicle engine

    def compute_composite(self) -> float:
        """Weighted composite score across all dimensions."""
        self.composite_score = (
            self.expected_return * 0.20
            + (1 - self.expected_risk) * 0.15
            + self.payoff_asymmetry * 0.15
            + (1 - self.timing_sensitivity) * 0.10
            + self.liquidity_quality * 0.10
            + self.implementation_simplicity * 0.05
            + self.robustness_to_error * 0.15
            - self.theta_decay_cost * 0.05
            - self.transaction_cost_bps / 100 * 0.05
        )
        return self.composite_score


@dataclass
class Proposal:
    """
    Full trade proposal generated by an agent for multi-stage review.

    This is the rich replacement for TradePick in the enhanced pipeline.
    """
    # Identity
    proposal_id: str = ""
    agent_id: str = ""
    timestamp: datetime = field(default_factory=datetime.now)

    # Asset
    symbol: str = ""
    sector: str = ""
    sub_industry: str = ""

    # Direction and type
    direction: str = "long"  # long | short
    investment_type: InvestmentType = InvestmentType.SHARES_SPOT
    thesis_type: ThesisType = ThesisType.TECHNICAL

    # Thesis
    thesis: str = ""  # text explanation of why
    strategy_used: str = ""
    catalyst: str = ""  # specific catalyst if event-driven
    has_defined_catalyst: bool = False

    # Conviction
    confidence: float = 0.0  # 0-1
    expected_edge_bps: float = 0.0  # expected alpha in basis points
    raw_score: float = 0.0

    # Time horizon
    time_horizon_days: int = 10
    holding_period_category: str = "swing"  # scalp|swing|position|macro

    # Sizing
    suggested_position_pct: float = 0.02  # % of portfolio
    kelly_fraction: float = 0.0

    # Volatility and liquidity
    expected_annual_vol: float = 0.0
    implied_vol: float = 0.0  # if options data available
    realized_vol: float = 0.0
    avg_daily_volume: float = 0.0
    avg_spread_bps: float = 0.0
    slippage_sensitivity: float = 0.0  # 0=insensitive, 1=very sensitive

    # Risk
    risks: ProposalRisks = field(default_factory=ProposalRisks)

    # Entry/exit logic
    entry_logic: str = ""
    exit_logic: str = ""
    stop_loss_pct: float = 0.0
    take_profit_pct: float = 0.0
    invalidation_price: float = 0.0

    # Vehicle candidates (populated by vehicle engine)
    vehicle_candidates: List[VehicleCandidate] = field(default_factory=list)
    selected_vehicle: Optional[VehicleCandidate] = None
    vehicle_rationale: str = ""

    # Review tracking
    peer_approved: bool = False
    peer_approval_pct: float = 0.0
    specialist_review_passed: bool = False
    specialist_confidence: float = 0.0
    specialist_objections: List[str] = field(default_factory=list)
    specialist_modifications: List[str] = field(default_factory=list)
    global_vote_passed: bool = False
    global_approval_pct: float = 0.0
    global_weighted_confidence: float = 0.0
    dissent_summary: str = ""

    # Portfolio layer
    portfolio_approved: bool = False
    final_position_pct: float = 0.0
    capital_allocated: float = 0.0

    @property
    def is_fully_approved(self) -> bool:
        """Check if proposal passed all pipeline stages."""
        return (
            self.specialist_review_passed
            and self.global_vote_passed
            and self.portfolio_approved
        )


def proposal_from_trade_pick(pick) -> Proposal:
    """Convert a legacy TradePick into a Proposal."""
    return Proposal(
        proposal_id=f"{pick.agent_id}_{pick.symbol}_{int(pick.timestamp.timestamp())}",
        agent_id=pick.agent_id,
        timestamp=pick.timestamp,
        symbol=pick.symbol,
        sector=pick.sector,
        sub_industry=getattr(pick, "sub_industry", ""),
        direction=pick.direction,
        confidence=pick.confidence,
        raw_score=pick.raw_score,
        strategy_used=pick.strategy_used,
        thesis=pick.reasoning,
        time_horizon_days=pick.suggested_hold_days,
        peer_approved=pick.peer_approved,
        peer_approval_pct=pick.peer_approval_pct,
    )
